apiVersion: v1
kind: Namespace
metadata:
  name: openshift-lws-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: leader-worker-set
  namespace: openshift-lws-operator
spec:
  targetNamespaces:
    - openshift-lws-operator
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:  
  name: leader-worker-set  
  namespace: openshift-lws-operator
  labels:
    operators.coreos.com/leader-worker-set.openshift-lws-operator: ''
spec:
  channel: stable-v1.0
  name: leader-worker-set
  source: redhat-operators
  sourceNamespace: openshift-marketplace
