exclude:
  # Exclude docs directory (contains alibiexplainer sample with keras 2.14.0)
  - "**/docs/**"
  - "**/charts/**"
  - "**/hack/**"
  - "**/hack/**"
  - "**/install/**"
  - "**/tools/**"

  # Exclude unneeded Python components
  - "**/python/aiffairness/**"
  - "**/python/artexplainer/**"
  - "**/python/custom_model/**"
  - "**/python/custom_tokenizer/**"
  - "**/python/custom_transformer/**"
  - "**/python/huggingfaceserver/**"
  - "**/python/lgbserver/**"
  - "**/python/paddleserver/**"
  - "**/python/plugin/**"
  - "**/python/pmmlserver/**"
  - "**/python/sklearnserver/**"
  - "**/python/test_resources/**"
  - "**/python/third_party/**"
  - "**/python/xgbserver/**"

  # Exclude unneeded Containerfiles
  - "**/aiffairness.Dockerfile"
  - "**/artexplainer.Dockerfile"
  - "**/custom_model.Dockerfile"
  - "**/custom_model_grpc.Dockerfile"
  - "**/custom_tokenizer.Dockerfile"
  - "**/custom_transformer.Dockerfile"
  - "**/custom_transformer_grpc.Dockerfile"
  - "**/error_404_isvc.Dockerfile"
  - "**/huggingface_server.Dockerfile"
  - "**/huggingface_server_cpu.Dockerfile"
  - "**/lgb.Dockerfile"
  - "**/paddle.Dockerfile"
  - "**/pmml.Dockerfile"
  - "**/sklearn.Dockerfile"
  - "**/success_200_isvc.Dockerfile"
  - "**/xgb.Dockerfile"
