releases:
  - name: KServe
    version: v0.21.0
    repoUrl: https://github.com/kserve/kserve/
  - name: vLLM
    version: v0.28.0
    repoUrl: https://github.com/vllm-project/vllm
  - name: llm-d-router
    version: v0.11.0
    repoUrl: https://github.com/llm-d/llm-d-router
  - name: llm-d-autoscaling
    version: v0.9.0
    repoUrl: https://github.com/llm-d/llm-d-autoscaling

