# Build container for the GKM MCV (Model Cache Vault) tool.
#
# MCV is used by the vllm-cache-builder pipeline to package vLLM compilation
# caches as OCI images. This Containerfile builds the mcv binary from source
# and bundles it into a minimal image.
#
# Build:
#   podman build -t quay.io/<your-org>/mcv:latest -f Containerfile.mcv .
#
# Push:
#   podman push quay.io/<your-org>/mcv:latest
#
# The pipeline references this image via the mcv-image parameter.
#
FROM registry.access.redhat.com/ubi9/go-toolset:1.22 AS builder

USER root

RUN dnf install -y gpgme-devel btrfs-progs-devel && dnf clean all

WORKDIR /build
RUN git clone --depth 1 https://github.com/redhat-et/GKM.git && \
    cd GKM/mcv && \
    make build

FROM registry.access.redhat.com/ubi9/ubi-micro:latest

COPY --from=builder /build/GKM/mcv/_output/local/bin/linux_amd64/mcv /usr/local/bin/mcv

ENTRYPOINT ["/usr/local/bin/mcv"]