name: Disconnected Readiness
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  check:
    uses: opendatahub-io/disconnected-readiness-scorer/.github/workflows/disconnected-readiness-check.yml@31eedf423156a22205e8044264e454612ddd9217 # storage-initializer exception
    with:
      rules: ""
